### ISSUE TITLE
Auto vs Manual Extraction

### ISSUE THREAD

**Issue by vukosim** [dsfsi/vukuzenzele-nlp#9]
Extract manually the second edition from July 

Try automatic extraction using 
1. https://github.com/euske/pdfminer
2. https://github.com/py-pdf/PyPDF2

**Comment by Daniel-Ind** [comment]
@vukosim 
@dupsys 

![Auto-Manual-Eng](https://user-images.githubusercontent.com/76164769/178978083-dfdee0a9-1a25-418c-b54f-8c84f27b1c91.PNG)

![Auto-Manual-AFR](https://user-images.githubusercontent.com/76164769/178978167-7bf178e2-2211-41a8-957a-0486674c2139.PNG)

- These are two examples of the English and Afrikaans articles. 
- The automatic is on the left and the manual is on the right.

I'm asking for a bit more time to refine the automatic method to apply to all the translations.

**Comment by Daniel-Ind** [comment]
I also have a question:
- On the automatic extraction, should the method automatically write to a txt file or should it only produce the extracted article for a person to copy onto a file manual?

**Comment by vukosim** [comment]
Can you then create a simple python script that you give it the page number(s) and it will extract into 11 txt files in the interim folder.

so it could be something like 
"vukuzenzele-extract.py  -f "filename" -eng "pagenum-pagenum" -rest "pagenum-pagenum"  -sn "story-number"

e.g.
vukuzenzele-extract.py -f "raw/2022-06-ed2//2022-06-ed2-vukuzenzele" -eng 11-12 -rest 4-5 -sn 001 
The example would extract from the english pages 11-12 (where the english story is) and page 4-5 where in the other languages the story would be

**Comment by Daniel-Ind** [comment]
@vukosim 
The script works with the format that you have given when run from the command line, although it differs on the **filename**, instead of mentioning the directory, the user only mentions the date and edition:
"vukuzenzele-extract.py -f "filename" -eng "pagenum-pagenum" -rest "pagenum-pagenum" -sn "story-number"

Example:
python "vukuzenzele-extract.py -f **2022-06-ed2** -eng 5-8 -rest 1-2 -sn 002
- It automatically searches the raw folder and extracts the results to the interim folder.

**Comment by vukosim** [comment]
Thanks @Daniel-Ind See my comment on your pull request 

Can you then do 2022. June, May and April for a couple of stories with the pull request of the code.

**Comment by Daniel-Ind** [comment]
@vukosim 
Pull request has been created with the 2022 stories and extraction script.
